### ISSUE TITLE
Describe encoding of injected XML

### ISSUE THREAD

**Issue by jmandel** [blue-button/bbClear#2]
https://github.com/blue-button/bbClear/blob/gh-pages/index.html#L57 -- should describe how to encode CCDA document before injecting (e.g. `.replace('<', '&lt;').replace('>', '&rt;')` or whatever is required).

**Comment by jmandel** [comment]
Hmm, looks like no encoding anymore? If so, can close.

**Comment by mjacksonw** [comment]
Yup, hopefully shouldn't need encoding. Fingers crossed.
